version: "3.8"
services:
  api:
    container_name: iban_api
    image: iban/api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
#    volumes:
#      - './:/app'
    depends_on:
      - db
      - redis
      - worker
    command: sh -c "
      sleep 5 && 
      alembic upgrade head && 
      uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

  worker:
    container_name: iban_worker
    image: iban/worker
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    command: sh -c "
      sleep 5 && 
      arq src.worker.WorkerSettings"

  db:
    container_name: iban_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iban_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    container_name: iban_redis
    image: 'bitnami/redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  tests:
    container_name: iban_tests
    image: iban/tests
    build:
      context: .
      dockerfile: Dockerfile
    command: pytest
    environment:
      - TESTING=TRUE
      - REDIS_URI=redis://redis:6379?db=1
    depends_on:
      - redis


volumes:
  db_data: