version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - './:/app'
    depends_on:
      - db
    command: sh -c "
      sleep 5 && 
      alembic upgrade head && 
      uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iban_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: pytest
    environment:
      - TESTING=TRUE


volumes:
  db_data: