"""Adding IBAN validations model

Revision ID: 84e60082b139
Revises: 
Create Date: 2023-10-01 00:57:14.643626

"""
from typing import Sequence, Union

import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

from src.iban.models import StatusTypes

# revision identifiers, used by Alembic.
revision: str = '84e60082b139'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'iban_validations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=34), nullable=False),
        sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(StatusTypes, impl=sa.Integer()), nullable=False),
        sa.Column('error_message', sa.String(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iban_validations_id'), 'iban_validations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iban_validations_id'), table_name='iban_validations')
    op.drop_table('iban_validations')
    # ### end Alembic commands ###
